services:
  scanner:
    build: .
    container_name: bcfy-scanner
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    command: ["41286", "40761", "--model", "medium", "--log-dir", "/app/logs", "--record-dir", "/app/recordings", "--feed-names", "41286:Bedford County,40761:Lynchburg Fire"]
    volumes:
      - bcfy-cache:/app/.cache
      - bcfy-logs:/app/logs
      - bcfy-recordings:/app/recordings
    networks:
      - traefik-net

  dashboard:
    build: .
    container_name: bcfy-dashboard
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    entrypoint: ["python", "dashboard.py"]
    command: ["--log-dir", "/app/logs", "--feed-names", "41286:Bedford County,40761:Lynchburg Fire", "--port", "8095", "--record-dir", "/app/recordings"]
    volumes:
      - bcfy-logs:/app/logs
      - bcfy-recordings:/app/recordings
    networks:
      - traefik-net

volumes:
  bcfy-cache:
  bcfy-logs:
  bcfy-recordings:

networks:
  traefik-net:
    external: true
